version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  assignees:
  - alexdaniel654
  labels:
  - dependencies
  ignore:
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
