language: python
dist: xenial
python:
  - 3.6
  - 3.7
cache: pip
before_install:
  - pip install codecov
install:
  - pip install -r requirements.txt
script:
  - ls -al
  - coverage run -m unittest discover
after_success:
  - codecov --token=$CODECOV_TOKEN